[package]
name = "funbuns_native"
version = "0.1.0"
edition = "2021"

[lib]
name = "funbuns_native"
crate-type = ["cdylib"]

[dependencies]
polars = { version = "0.48", default-features = false, features = ["dtype-i8", "dtype-u8", "dtype-struct"] }
polars-arrow = { version = "0.48" }
pyo3 = { version = "0.24", features = ["extension-module"] }
pyo3-polars = { version = "0.21", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
rug = "1"
