[workspace]
authors = ["Eric Page <genamthi@gmail.com>"]
channels = ["conda-forge"]
name = "funbuns"
platforms = ["linux-64"]
version = "0.1.1"

[tasks]
serve = "python -m http.server 8000 -d data"

[dependencies]
polars = ">=1.32.0,<2"
sagelib = ">=10.6,<11"
altair = ">=5.5.0,<6"
tqdm = ">=4.67.1,<5"
psutil = ">=7.0.0,<8"

[tool.funbuns]
buffer_size = 10000


[pypi-dependencies]
funbuns = { path = ".", editable = true }

