[workspace]
authors = ["Eric Page <genamthi@gmail.com>"]
channels = ["conda-forge"]
name = "funbuns"
platforms = ["linux-64"]
version = "0.1.1"

[tasks]
serve = "python -m http.server 8000 -d data"
bmgr = "python -m funbuns.block_manager"
bmgr-integrate = "python -m funbuns.block_manager --integrate-check"
bmgr-integrity = "python -m funbuns.block_manager --integrity"

[dependencies]
sagelib = ">=10.6,<11"
altair = ">=5.5.0,<6"
tqdm = ">=4.67.1,<5"
psutil = ">=7.0.0,<8"

[tool.funbuns]
buffer_size = 10000
small_primes_filename = "small_primes.parquet"
lim_sm_p = 100000
max_power = 64
use_separate_runs = true

[tool.funbuns.directories]
data_dir = "data"
blocks_dir = "data"
backup_dir = "data/backups"
temp_dir = "data/tmp"


[pypi-dependencies]
funbuns = { path = ".", editable = true }
polars = { path = "/home/erpage159/fluid/byo/repos/polars/target/wheels/polars-1.32.0b1-cp39-abi3-manylinux_2_39_x86_64.whl" }

[environments]
dev = []

[tool.pixi.feature.dev.dependencies]
sage = ">=10.6"

[tool.pixi.environments]
dev = ["dev"]
