[workspace]
authors = ["Eric Page <genamthi@gmail.com>"]
channels = ["conda-forge"]
name = "funbuns"
platforms = ["linux-64"]
version = "0.1.1"

[tasks]
serve = "python -m http.server 8000 -d data"
bmgr = "python -m funbuns.block_manager"
bmgr-integrate = "python -m funbuns.block_manager --integrate-check"
bmgr-integrity = "python -m funbuns.block_manager --integrity"
ladic = "funbuns --ladic"
build-native = "cd funbuns_native && maturin develop --release"

[dependencies]

altair = ">=6.0.0,<7"
tqdm = ">=4.67.3,<5"
psutil = ">=7.2.2,<8"
polars = ">=1.38.1,<2"
py-spy = ">=0.4.1,<0.5"
python = "==3.13.5"

[tool.funbuns]
buffer_size = 10000
small_primes_filename = "small_primes.parquet"
lim_sm_p = 100000
max_power = 64

[tool.funbuns.directories]
data_dir = "data"
runs_dir = "data/runs"
blocks_dir = "data/blocks"
backup_dir = "data/backups"
temp_dir = "data/tmp"


[pypi-dependencies]
funbuns = { path = ".", editable = true }
sagemath = ">=10.8, <11"

[environments]
dev = []

[tool.pixi.feature.dev.dependencies]
sage = ">=10.8"

[tool.pixi.environments]
dev = ["dev"]
